openapi: 3.0.3
info:
  title: Express Booster API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 1.0.0
servers:
  - url: /
    description: Local development
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /:
    get:
      summary: Return a response that indicates server is running
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A string
          content:
            application/json:
              schema:
                type: string

  /admin/users:
    get:
      tags:
        - 'admin'
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
