version: 2.1
jobs:
  unit-test:
    docker:
      - image: circleci/node:12.14.1
    working_directory: ~/

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install NPM Packages
          command: npm install

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "./app/package.json" }}

      # run tests!
      - run:
          name: run tests
          command: npm run test-ci

      - store_artifacts:
          path: test-results.xml

      - store_artifacts:
          path: coverage

